title: INF-2201-1 25V Operating system fundamentals (edit _config.yml)

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: wtr003@uit.no
  name: Willy Kiet Tran (edit _config.yml)

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
